### ISSUE TITLE
Direct vuex state mutation 

### ISSUE THREAD

**Issue by mwangi-njuguna** [inmdigitalfactory/asset-finance#54]
Refrain from mutating store directly as it's supposed to be Predictable.

https://github.com/inmdigitalfactory/asset-finance/blob/269e6eb932fe440c04c6d6b0f1a1c1eae8335500/src/components/calculator/LoanCalculator.vue#L331

Check https://vuex.vuejs.org/guide/mutations.html

**Comment by MbuguaMwaura** [comment]
I have removed that mutation. I was not even supposed to be there in the first place. Thanks for noticing it.
