### ISSUE TITLE
Replace *var* with *let*

### ISSUE THREAD

**Issue by mwangi-njuguna** [inmdigitalfactory/asset-finance#55]
In javascript, as variables lose scope, they become eligible for garbage collection. If they are scoped globally(var), then they will not be eligible for collection until the global namespace loses scope. This leads to more memory usage. Moreover, there might be variable shadowing which might be hard to debug.

I suggest using [vue-eslint](https://github.com/vuejs/eslint-plugin-vue) which is extended from [eslint](https://eslint.org/) as it helps in flagging such issues

example-usage:
https://github.com/inmdigitalfactory/asset-finance/blob/269e6eb932fe440c04c6d6b0f1a1c1eae8335500/src/components/calculator/LoanCalculator.vue#L245

**Comment by MbuguaMwaura** [comment]
We have replaced all var instanced with let or const depending on the variable.
