### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by mwangi-njuguna** [inmdigitalfactory/asset-finance#56]
Please refrain from using magic numbers as it is hard for other people to understand.

example usage of magic numbers:
https://github.com/inmdigitalfactory/asset-finance/blob/269e6eb932fe440c04c6d6b0f1a1c1eae8335500/src/components/calculator/LoanCalculator.vue#L249

**Comment by MbuguaMwaura** [comment]
I have removed all of the instances of magic numbers. Thanks for the heads up on the issue
