### ISSUE TITLE
Axios usage

### ISSUE THREAD

**Issue by mwangi-njuguna** [inmdigitalfactory/asset-finance#57]
Axios is a **Promise** based HTTP client for the browser and node.js hence wrapping it with another Promise is incorrect.
Check usage here https://github.com/axios/axios
and consider refactoring this.

https://github.com/inmdigitalfactory/asset-finance/blob/809250ffaae264828438329af78947d69e0ae5dd/src/services/api-connector/ApiConnector.js#L6

**Comment by MbuguaMwaura** [comment]
we have changed the axios implementation and corrected the issue. Thanks for the input
